GET http://localhost:8080/

###

GET http://localhost:8080/esquadrao/

###

GET  http://localhost:8080/esquadrao

###

POST http://localhost:8080/esquadrao
Content-Type: application/json

{
    "nome": "Touros Negros"
}

###
PUT http://localhost:8080/esquadrao?id=417a118c-7994-4c76-bccd-43e9acee384c
Content-Type: application/json

{
    "nome": "Aguias de Prata"
}

###
DELETE http://localhost:8080/esquadrao?id=b34a6b71-323c-477d-b764-ee4a8c6e4dfc