GET http://localhost:8080/

###

GET http://localhost:8080/esquadrao/2

###

GET  http://localhost:8080/esquadrao

###

POST http://localhost:8080/esquadrao
Content-Type: application/json

{
    "nome": "Touros Negros"
}

###
PUT http://localhost:8080/esquadrao?id=2
Content-Type: application/json

{
    "nome": "Alvorecer Dourado"
}

###
DELETE http://localhost:8080/esquadrao?id=3