GET http://localhost:8080/

###

GET  http://localhost:8080/membros/393c4662-3543-4f61-87c0-8bc7529631a2

###
GET http://localhost:8080/membros

###
POST http://localhost:8080/membros
Content-Type: application/json

{
    "nome": "Noele",
    "magia": "Agua"
    
}
###
PUT http://localhost:8080/membros?id=fb35cc70-99e9-40b5-b811-f434428c0b94
Content-Type: application/json

{
    "nome": "Nozel"
}

###
DELETE http://localhost:8080/membros?id=f58d0738-4735-4b10-8867-6246caa6b619