GET http://localhost:8080/

###

GET  http://localhost:8080/membros/1

###
GET http://localhost:8080/membros

###
POST http://localhost:8080/membros
Content-Type: application/json

{
    "nome": "Asta",
    "magia": "Anti-Magia ",
    "ranking": "Cavaleiro"
}
###
PUT http://localhost:8080/membros?id=2
Content-Type: application/json

{
    "nome": "Luke",
    "magia": "Raio",
    "ranking": "Cavaleiro"

}

###
DELETE http://localhost:8080/membros?id=3